"""empty message

Revision ID: 434ce2a67802
Revises: e9dd858c4469
Create Date: 2024-01-31 22:22:38.772778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434ce2a67802'
down_revision = 'e9dd858c4469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    with op.batch_alter_table('favorite_park', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_park_park_id_fkey', type_='foreignkey')
    op.drop_table('park')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_park', schema=None) as batch_op:
        batch_op.create_foreign_key('favorite_park_park_id_fkey', 'park', ['park_id'], ['id'])

    op.create_table('park',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='park_pkey')
    )
    # ### end Alembic commands ###
